# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/hllsy/OneDrive/Masaüstü/Bilgisayar Programlama/PYTHON/MODÜLLER/PyQt5/Projects/Asal Sayılar Oyunu/Asal_Sayılar_Oyunu.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(732, 518)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 1000))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/WindowIcon/icons/Icon.6_06.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 521, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setStyleSheet("background-color: rgb(255, 197, 245);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 501, 141))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(" \n"
" \n"
" \n"
"font: 75 13pt \"Times New Roman\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 731, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet(" \n"
" \n"
"background-color: rgb(170, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        self.label.setProperty("font_type", font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(520, 80, 211, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_skor = QtWidgets.QLabel(self.groupBox)
        self.label_skor.setGeometry(QtCore.QRect(40, 80, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_skor.setFont(font)
        self.label_skor.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.label_skor.setText("")
        self.label_skor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_skor.setObjectName("label_skor")
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 250, 731, 271))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_oyunEkran = QtWidgets.QLabel(self.groupBox_2)
        self.label_oyunEkran.setGeometry(QtCore.QRect(310, 20, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_oyunEkran.setFont(font)
        self.label_oyunEkran.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.label_oyunEkran.setText("")
        self.label_oyunEkran.setAlignment(QtCore.Qt.AlignCenter)
        self.label_oyunEkran.setObjectName("label_oyunEkran")
        self.pushButton_dogru = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_dogru.setGeometry(QtCore.QRect(180, 150, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_dogru.setFont(font)
        self.pushButton_dogru.setStyleSheet("border-radius: 15px;\n"
" \n"
"background-color: rgb(170, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Butontuslari/icons/dogruTusu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dogru.setIcon(icon1)
        self.pushButton_dogru.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_dogru.setObjectName("pushButton_dogru")
        self.pushButton_yanlis = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_yanlis.setGeometry(QtCore.QRect(440, 150, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_yanlis.setFont(font)
        self.pushButton_yanlis.setStyleSheet("border-radius: 15px;\n"
" \n"
" \n"
"background-color: rgb(255, 43, 75);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Butontuslari/icons/yanlısTusu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_yanlis.setIcon(icon2)
        self.pushButton_yanlis.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_yanlis.setObjectName("pushButton_yanlis")
        self.verticalLayout_4.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Asal Sayılar Oyunu"))
        self.label_2.setText(_translate("MainWindow", "Toplam 10 soru bulunmakta \n"
" ve size bunlardan asal olanlar sorulmaktadır.\n"
"Her Doğru Cevabınız için 10 puan alacaksınız. Başarılar."))
        self.label.setText(_translate("MainWindow", "ASAL SAYILAR OYUNU"))
        self.groupBox.setTitle(_translate("MainWindow", "Skor Ekranı"))
        self.label_4.setText(_translate("MainWindow", "SKOR:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Oyun Ekranı"))
        self.pushButton_dogru.setText(_translate("MainWindow", "DOĞRU"))
        self.pushButton_yanlis.setText(_translate("MainWindow", "YANLIŞ"))

import ikonlar_rc
